version: 0.2

phases:
  install: 
    runtime-versions:
      golang: 1.13
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - export GO111MODULE="on" 

  build:
    commands:
      - echo Build started on `date`
      - echo Getting packages
      - go get ./...
      - echo Compiling the Go code...
      - go build -o gogs gogs.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - gogs
    - buildspec.yml
    - appspec.yml
    - production.conf	
    - infrastructure.yml
    - codedeploy/*
