version: 0.2

phases:
  install: 
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - export GO111MODULE="on" 

  build:
    commands:
      - echo Build started on `date`
      - echo Getting packages
      - go get -u ./...
      - echo Compiling the Go code...
      - go build -o gogs gogs.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - gogs
